{% set version = '3.12.0' %}
{% set sha256 = '1a02fa0336c27583aabf399124ac0610ef20452cf6b837a1082f7788f17fadad' %}
# FIXME: bitbucket sets the wrong content-encoding headers, resulting in downloading the unzipped .tar file
# rather than the tar.gz file
{% set sha256 = 'fe3b189e77736bc0206ce28c5caa573dc97a829975f31fd6e8fa6f3e2512d719' %}

{% set mpi = mpi or 'mpich' %}

package:
  name: petsc4py
  version: {{version}}

source:
  fn: petsc4py-{{version}}.tar
  url: https://bitbucket.org/petsc/petsc4py/downloads/petsc4py-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  number: 5
  script: PETSC_DIR=$PREFIX pip -v install --no-deps .
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - {{ mpi }}
    - petsc {{version.rsplit('.', 1)[0]}}.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}
    - petsc # pinned by petsc run_exports

about:
  home: https://bitbucket.org/petsc/petsc4py
  summary: Python bindings for PETSc
  license: BSD 2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
