{% set name = "petsc4py" %}
{% set version = "3.21.1" %}  # TODO: remove Cython pinning for petsc4py-3.20.0
{% set sha256 = "ea8c6afb16541167d39f87d5fcad98c32d856fe8a2173504ef2a31c16647d53d" %}
{% set build = 1 %}

{% set version_xy = version.rsplit('.', 1)[0] %}

package:
  name: petsc4py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script:
    - {{ PYTHON }} conf/cythonize.py
    - export OPAL_PREFIX=$PREFIX  # [mpi == 'openmpi']
    - export PETSC_DIR=$PREFIX
    - {{ PYTHON }} -m pip -v install --no-deps .
  skip: true  # [win]
  skip: true  # [osx and device != "host"]
  string: {{ scalar }}_h{{ PKG_HASH }}_{{ build }}               # [device == 'host']
  string: {{ device }}_{{ scalar }}_h{{ PKG_HASH }}_{{ build }}  # [device != 'host']
  track_features:
    - petsc4py_complex  # [scalar == "complex"]
    - petsc4py_cuda     # [device != "host"]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                              # [build_platform != target_platform]
    - cython 0.29.36                      # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - python
    - cython 0.29.36
    - pip
    - numpy
    - {{ mpi }}
    - petsc {{ version_xy }}.* {{ scalar }}_*               # [device == 'host']
    - petsc {{ version_xy }}.* {{ device }}_{{ scalar }}_*  # [device != 'host']
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}
    - petsc  # pinned by petsc run_exports
  run_constrained:
    - mpi4py >=3.0.1

about:
  home: https://bitbucket.org/petsc/petsc4py
  summary: Python bindings for PETSc
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
    - stefanozampini
