{% set name = "petsc4py" %}
{% set version = "3.17.1" %}
{% set sha256 = "f73a6eb0b453ec2500c9b353dc8427f205bcc12910b263bc4351fea3c6e0af71" %}
{% set build = 1 %}

{% set version_xy = version.rsplit('.', 1)[0] %}
{% if scalar == "real" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: petsc4py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script:
    - export OPAL_PREFIX=$PREFIX  # [mpi == 'openmpi']
    - export PETSC_DIR=$PREFIX
    - {{ PYTHON }} -m pip -v install --no-deps .
  skip: true  # [win]
  string: {{ scalar }}_h{{ PKG_HASH }}_{{ build }}
  track_features:
    - petsc4py_complex  # [scalar == "complex"]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - python
    - pip
    - numpy
    - {{ mpi }}
    - petsc {{ version_xy }}.* *{{ scalar }}*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}
    - petsc * *{{ scalar }}*  # pinned by petsc run_exports
  run_constrained:
    - mpi4py >=3.0.1

about:
  home: https://bitbucket.org/petsc/petsc4py
  summary: Python bindings for PETSc
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
