{% set name = "petsc4py" %}
{% set version = "3.18.5" %}
{% set sha256 = "625cbb99d7d3000ad05afe60585c6aa24ca650894b09a1989127febb64b65470" %}
{% set build = 0 %}

{% set version_xy = version.rsplit('.', 1)[0] %}
{% if scalar == "real" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: petsc4py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script:
    - {{ PYTHON }} conf/cythonize.py
    - export OPAL_PREFIX=$PREFIX  # [mpi == 'openmpi']
    - export PETSC_DIR=$PREFIX
    - {{ PYTHON }} -m pip -v install --no-deps .
  skip: true  # [win]
  string: {{ scalar }}_h{{ PKG_HASH }}_{{ build }}
  track_features:
    - petsc4py_complex  # [scalar == "complex"]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - python                              # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - python
    - cython
    - pip
    - numpy
    - {{ mpi }}
    - petsc {{ version_xy }}.* {{ scalar }}_*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}
    - petsc  # pinned by petsc run_exports
  run_constrained:
    - mpi4py >=3.0.1

about:
  home: https://bitbucket.org/petsc/petsc4py
  summary: Python bindings for PETSc
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
