{% set name = 'petsc4py' %}
{% set version = '3.13.0' %}
{% set sha256 = 'ace21f71102e752fefac6c81b65207edba89a6974b3c58c71599c6c358640f39' %}

{% set version_xy = version.rsplit('.', 1)[0] + ".*" %}

package:
  name: petsc4py
  version: {{ version }}

source:
  fn: petsc4py-{{version}}.tar
  url: https://pypi.io/packages/source/{{name[0]}}/{{name}}/{{name}}-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  number: 1
  script: PETSC_DIR=$PREFIX pip -v install --no-deps .
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - {{ mpi }}
    - petsc {{ version_xy }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}
    - petsc # pinned by petsc run_exports
  run_constrained:
    - mpi4py >=3.0.1

about:
  home: https://bitbucket.org/petsc/petsc4py
  summary: Python bindings for PETSc
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
